<?xml version="1.0"?>

<robot name="scout_mini" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="urdf_extras" default="scout_mini_extras.urdf" /> 

    <!-- Vehicle Geometries -->
    <xacro:property name="wheelbase" value="0.3132556"/>
    <xacro:property name="track" value="0.4563536" />
    <xacro:property name="wheel_vertical_offset" value="-0.077" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0.015 0.0231316650320557 0" rpy="1.57 0 -1.57"/>
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_mini_base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.015 0.0231316650320557 0" rpy="1.57 0 -1.57"/>
          <geometry>
            <mesh
              filename="package://scout_description/meshes/scout_mini_base_link.dae" />
          </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="132.3898489950015" />
            <origin xyz="0.015 0.0231316650320557 0" />
            <inertia ixx="0.185196122711036" ixy="4.30144213829512E-08" ixz="5.81037523686401E-08"
            iyy="0.364893736238929" iyz="-0.000386720198091934" izz="0.223868521722778" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>
  
    <!-- Scout wheel macros -->
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.7171" iyz="0" izz="0.1361" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/wheel.dae" />
            </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://scout_description/meshes/wheel.dae" />
          </geometry>
        </collision>
    </link>

    <joint name="front_right_wheel" type="continuous">
        <origin xyz="${track/2} ${-wheelbase/2} ${wheel_vertical_offset}" rpy="1.57 0 0" />
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <axis xyz="0 0 -1" rpy="0 0 0" />
    </joint>

    <link name="front_left_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.7171" iyz="0" izz="0.1361" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/wheel.dae" />
            </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://scout_description/meshes/wheel.dae" />
          </geometry>
        </collision>
    </link>

    <joint name="front_left_wheel" type="continuous">
        <origin xyz="${track/2} ${wheelbase/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <axis xyz="0 0 1" rpy="0 0 0" />
    </joint>

    <link name="rear_right_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.7171" iyz="0" izz="0.1361" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/wheel.dae" />
            </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://scout_description/meshes/wheel.dae" />
          </geometry>
        </collision>
    </link>

    <joint name="rear_right_wheel" type="continuous">
        <origin xyz="${-track/2} ${-wheelbase/2} ${wheel_vertical_offset}" rpy="1.57 0 0" />
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <axis xyz="0 0 -1" rpy="0 0 0" />
    </joint>

    <link name="rear_left_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.7171" iyz="0" izz="0.1361" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/wheel.dae" />
            </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://scout_description/meshes/wheel.dae" />
          </geometry>
        </collision>
    </link>

    <joint name="rear_left_wheel" type="continuous">
        <origin xyz="${-track/2} ${wheelbase/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <axis xyz="0 0 1" rpy="0 0 0" />
    </joint>
  
    <!-- plug-in -->
    <plugin name='scout_mini_joint_state' filename='libgazebo_ros_joint_state_publisher.so'>
      <ros>
        <namespace>/robot_namespace</namespace>
        <remapping>~/out:=joint_states</remapping>
      </ros>
      
      <update_rate>50</update_rate>
      
      <joint_name>front_right_wheel</joint_name>
      <joint_name>front_left_wheel</joint_name>
      <joint_name>rear_right_wheel</joint_name>
      <joint_name>rear_left_wheel</joint_name>

    </plugin>      

    <plugin name='skid_steer_drive' filename='libgazebo_ros_diff_drive.so'>
      <!-- topics & remappings -->
      <ros>
        <namespace>/robot_namespace</namespace>
        <remapping>/tf:=tf</remapping>
      </ros>
      
      <!-- Update rate -->
      <update_rate>50</update_rate>

      <!-- Number of wheel pairs -->
      <num_wheel_pairs>2</num_wheel_pairs>
        
      <!-- front wheels -->
      <left_joint>front_left_wheel</left_joint>
      <right_joint>front_right_wheel</right_joint>

      <!-- rear wheels-->
      <left_joint>rear_left_wheel</left_joint>
      <right_joint>rear_right_wheel</right_joint>

      <!-- kinematics -->
      <wheel_separation>0.490</wheel_separation>
      <wheel_separation>0.490</wheel_separation>
      <wheel_diameter>0.160</wheel_diameter>
      <wheel_diameter>0.160</wheel_diameter>
              
      <!-- limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf> 
      <publish_wheel_tf>false</publish_wheel_tf> 

      <odometry_frame>odom</odometry_frame>
      <odometry_topic>odom</odometry_topic>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>

    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" /> 
</robot>
